### ISSUE TITLE
file missing: Plugins/LICENSE/LICENSEPlugin.class.php

### ISSUE THREAD

**Issue by W4rlock34** [nuxsmin/sysPass-Plugins#1]
Combining the newest master branch of nuxsmin/sysPass@a2858ed78e1681eed0055c69b29841976c7079c6  and sysPass-Plugins 6bc993745acd4c9c19d0a2cac04b7c0744793e53 gives me this error:

```
PHP Warning:  require(/var/www/html/syspass/inc/Plugins/LICENSE/LICENSEPlugin.class.php): failed to open stream: No such file or directory in /var/www/html/syspass/inc/SplClassLoader.php
PHP Fatal error:  require(): Failed opening required '/var/www/html/syspass/inc/Plugins/LICENSE/LICENSEPlugin.class.php' (include_path='.:/usr/share/php') in /var/www/html/syspass/inc/SplClassLoader.php on line 173
```

**Comment by nuxsmin** [comment]
Hmmm, that's weird because you only need to put the `Authenticator` dir into sysPass `Plugins` dir:

![captura_007](https://user-images.githubusercontent.com/1775774/29562864-63f34666-873b-11e7-9915-413d909367e6.png)

**Comment by W4rlock34** [comment]
I don´t know, but it´s true that the file does not exist

```
/var/www/html/syspass/inc/Plugins # tree -L 2
.
├── Authenticator
│   ├── ActionController.class.php
│   ├── ajax
│   ├── Authenticator.class.php
│   ├── AuthenticatorData.class.php
│   ├── AuthenticatorPlugin.class.php
│   ├── Google2FA.class.php
│   ├── js
│   ├── locales
│   ├── LoginController.class.php
│   ├── PreferencesController.class.php
│   ├── Session.class.php
│   └── themes
├── CODE_OF_CONDUCT.md
├── LICENSE
├── README.md
└── version.json
```

**Comment by nuxsmin** [comment]
It seems that the class loader is trying to include some files, please remove them from the Plugins dir root.

**Comment by W4rlock34** [comment]
Which file shall i delete now?
`/var/www/html/syspass/inc/SplClassLoader.php` ?

**Comment by nuxsmin** [comment]
You need to delete these instead:

```
├── CODE_OF_CONDUCT.md
├── LICENSE
├── README.md
└── version.json
```

**Comment by W4rlock34** [comment]
Ah, that did the trick. Thanks
So this means atm you are not allowed to have the plugins repo used as a submodule

**Comment by nuxsmin** [comment]
Great!. It shouldn't try to include those files, so I'll try to find out why is it including them.

Regards
