### ISSUE TITLE
Issue with new Authenticator plugin 

### ISSUE THREAD

**Issue by jr-RXcode** [nuxsmin/sysPass-Plugins#2]
update syspass to the latest release 2.1.12 and also the Authenticator plugin 1.1.0. 
I like the feature about getting a temporary code emailed, the issue is that once i log in i want to disable the 2 factor authentication but i get an error saying i need to enter a code. How would a disable the two factor ? Was the plug in suppose to disable the two factor ? 

Please advice, thanks!

**Comment by nuxsmin** [comment]
Hmm, you would need to enter some 6 digit code and then check the recovery code option. Lastly  click on login button. This will send to you àn email with a recovery code so you would be able to pass 2fa auth by entering this code.

Regards

**Comment by jr-RXcode** [comment]
Yes. the recover code works just fine. The issue is, how to disable the 2fa once your logged in. In order to disable the 2fa it is asking for a code to be enter, which you wouldn't have if you requested a recovery code  to be emailed. 

Is it possible to leave the QR code on that page so that you can add another device once you requested a recovery code, looks like once you add a device for the first time the QR code disappears ?

**Comment by nuxsmin** [comment]
It should display an eye icon on the security tab, so by clicking on it the recovery codes will be displayed, then using one of them, you will be able to disable 2fa Auth

**Comment by jr-RXcode** [comment]
I see the Recovery Codes eye icon,its grayed out, when I open inspect element and click on the eye I get the following message:                                                                                                                                   js.php?g=1&v=bfb52f1aca91a08db07e876b17fb9d5a:16 Uncaught TypeError: Cannot read property 'viewRecoveryCodes' of undefined
    at HTMLElement.<anonymous> (js.php?g=1&v=bfb52f1aca91a08db07e876b17fb9d5a:16)
    at HTMLBodyElement.dispatch (js.php?v=bfb52f1aca91a08db07e876b17fb9d5a:100)
    at HTMLBodyElement.n.handle (js.php?v=bfb52f1aca91a08db07e876b17fb9d5a:96)
(anonymous) @ js.php?g=1&v=bfb52f1aca91a08db07e876b17fb9d5a:16
dispatch @ js.php?v=bfb52f1aca91a08db07e876b17fb9d5a:100
n.handle @ js.php?v=bfb52f1aca91a08db07e876b17fb9d5a:96

**Comment by nuxsmin** [comment]
Which sysPass version are you running?. It might that you need to update sysPass code by downloading from the master branch. This upgrade will be seamless since there isn't any db upgrade, only minor changes and improvements. 

It hasn't been released yet as a version because I'm working on a export improvement, so it will be rolled out shortly.

Regards

**Comment by jr-RXcode** [comment]
Im running the latest version 2.1.12. I can wait until the new release comes out then.

**Comment by nuxsmin** [comment]
Please download it from the master branch https://github.com/nuxsmin/sysPass/archive/master.zip

**Comment by jr-RXcode** [comment]
I've downloaded and installed master along with the latest plugin version. When I try to disable the plugin it says "2fa has been disable", but the page refreshes and the plugin is still enable. I log out log back in and the plugin is still enable. I don't see any errors after trying to disable the plugin. Any advise ? 

Also, how can you reset the number of recovery codes, I used all my recovery codes when testing the disabling of the plugin , so now I have used them all and when I click on the eye icon it says there are no more codes available. Thanks for a ll your help !
