### ISSUE TITLE
Code unavailable

### ISSUE THREAD

**Issue by romainchassaigne** [nuxsmin/sysPass-Plugins#3]
Hey,

I dockerized syspass-app and add Authenticator plugins. But each time the app said the code is not available. Any idea ?

**Comment by nuxsmin** [comment]
Hi!

Did you download the Authenticator plugin within the plugins directory?. It should be a subdirectory within it.

Regards

**Comment by romainchassaigne** [comment]
Hello,

Yes I did. My Google Authenticator is well showing the code thanks to the QR code, but still invalid.

Regards.

**Comment by nuxsmin** [comment]
Hello, sorry, I misunderstood your issue. It seems that the sysPass container doesn't have the same clock time, because your Authenticator device clock time need to match with the container one.

Regards
